name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0

      
